apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: bgppeers.bgppeer.acnodal.com
spec:
  group: bgppeer.acnodal.com
  names:
    kind: Bgppeer
    listKind: BgppeerList
    plural: bgppeers
    singular: bgppeer
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
---
apiVersion: bgppeer.acnodal.com/v1alpha1
kind: Bgppeer
metadata:
  name: bgppeer
  namespace: arbf-operators
spec:
  metallb_namespace: metallb-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: arbf-bgppeer-operator
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: arbf-bgppeer-operator
subjects:
- kind: ServiceAccount
  namespace: arbf-operators
  name: arbf-bgppeer-operator
roleRef:
  kind: ClusterRole
  name: arbf-bgppeer-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: arbf-bgppeer-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - services/status
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - arbf-bgppeer-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  - deployments
  verbs:
  - get
- apiGroups:
  - bgppeer.acnodal.com
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arbf-bgppeer-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: arbf-bgppeer-operator
  template:
    metadata:
      labels:
        name: arbf-bgppeer-operator
    spec:
      serviceAccountName: arbf-bgppeer-operator
      containers:
        - name: ansible
          command:
          - /usr/local/bin/ao-logs
          - /tmp/ansible-operator/runner
          - stdout
          # Replace this with the built image name
          image: "acnodal/bgppeer-operator:v0.0.1"
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
            readOnly: true
          - name: ssh-key
            mountPath: /tmp/key
            readOnly: true
        - name: operator
          image: "acnodal/bgppeer-operator:v0.0.1"
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          - name: ssh-key
            mountPath: /tmp/key
            readOnly: true
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "arbf-bgppeer-operator"
            - name: ANSIBLE_GATHERING
              value: explicit
      volumes:
        - name: runner
          emptyDir: {}
        - name: ssh-key
          secret:
            secretName: ansible-operator-ssh
        
