apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: bgppeers.bgppeer.acnodal.com
spec:
  group: bgppeer.acnodal.com
  names:
    kind: Bgppeer
    listKind: BgppeerList
    plural: bgppeers
    singular: bgppeer
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
